services:

  db:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - prod.env
    logging:
      options:
        max-size: "5m"
        max-file: "3"

  redis_pr:
    image: "redis:8.0-alpine"
    restart: unless-stopped
    expose:
      - "6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_pr_data:/data
    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      options:
        max-size: "5m"
        max-file: "3"

  app:
    build:
      context: ./app
    restart: unless-stopped
    entrypoint: /app/entrypoint.prod.sh
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 4 --timeout 600 --max-requests 1000 --max-requests-jitter 50 --access-logfile - --error-logfile -
    volumes:
      - app_volume:/vol/app
    expose:
      - "8000"
    env_file:
      - prod.env
    depends_on:
      - db
      - redis_pr
    logging:
      options:
        max-size: "5m"
        max-file: "3"

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - app_volume:/vol/app
      - ./webserver/nginx:/etc/nginx/conf.d
      - ./webserver/certbot/conf:/etc/letsencrypt
      - ./webserver/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./webserver/certbot/conf:/etc/letsencrypt
      - ./webserver/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  db_volume:
  app_volume:
  redis_pr_data:
